# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Context', models.TextField()),
                ('User_name', models.CharField(max_length=25)),
                ('Add_time', models.DateTimeField()),
                ('Edit_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Context', models.TextField()),
                ('User_name', models.CharField(max_length=25)),
                ('Add_time', models.DateTimeField()),
                ('Edit_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=25)),
                ('Introduction', models.TextField()),
                ('Contact', models.TextField()),
                ('Photo', models.ImageField(upload_to='')),
                ('Add_time', models.DateTimeField()),
                ('Edit_time', models.DateTimeField()),
            ],
        ),
    ]
