# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-12 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omniscient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='Issue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omniscient.Issue'),
        ),
    ]
