# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-20 16:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omniscient', '0002_board_issue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='Issue',
        ),
        migrations.AddField(
            model_name='works',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
