# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-06 14:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omniscient', '0004_auto_20181204_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='User_name',
        ),
        migrations.AddField(
            model_name='issue',
            name='User',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
