# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-07 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omniscient', '0005_auto_20181206_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='Add_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='works',
            name='Edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
